### ISSUE TITLE
Higher-quality interpolation algorithms

### ISSUE THREAD

**Issue by Splendide-Imaginarius** [rainefall/mkxp-zr#2]
Currently, mkxp-zr only supports nearest-neighbor and bilinear interpolation (controlled by the `smoothScaling` config option). Would you be open to PR's that add higher-quality alternatives? I currently have Lanczos and xBRZ working, and bicubic should be pretty easy to add too. Lanczos tends to be excellent for CG images; bicubic is a good alternative for CG images if Lanczos causes too much ringing; xBRZ tends to be better than Lanczos/bicubic for character sprites and some tilesets.

If a PR would be welcome, what's the best interface to use for the config file? Adding more boolean options for the extra interpolation methods seems unclean, since only one will be active at once. Maybe replace the boolean `smoothScaling` option with a string `scaling` option, which accepts names like `nearest`, `linear`, etc.?

**Comment by rainefall** [comment]
PRs definitely welcome, as for the config interface I'd lean towards scaling being a numerical option, with 0 being nearest, then 1 2 + being linear, lanczos etc with documentation on which number is which. Both because RGSS already does a lot of enum style parameters this way and because it should be less error prone when editing the config and if/when adjusting the scaling mode at runtime (because Graphics#smooth_scaling would need to be changed to account for all of this)

**Comment by Splendide-Imaginarius** [comment]
Good points; numerical option sounds good to me. I'll see if I can fix up my patches to do it that way, and then send in some PR's.
